# Generated by Django 3.0.5 on 2020-06-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200605_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='office',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(user__groups__name='Manager'), on_delete=django.db.models.deletion.CASCADE, related_name='office_contact', to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(user__groups__name='Client'), on_delete=django.db.models.deletion.CASCADE, related_name='client_contact', to='users.Profile'),
            preserve_default=False,
        ),
    ]
