# Generated by Django 3.0.5 on 2020-06-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200606_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signature',
        ),
    ]
