# Generated by Django 3.0.5 on 2020-04-20 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
