# Generated by Django 3.0.5 on 2020-04-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200420_1452'),
        ('users', '0004_auto_20200420_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
