# Generated by Django 3.0.5 on 2020-04-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200425_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(limit_choices_to={'company__user__groups__name': 'Client'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
