# Generated by Django 3.0.5 on 2020-05-14 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20200514_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(default='321 ave', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default='Vancouver', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='CA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.CharField(default='BC', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
