# Generated by Django 3.0.5 on 2020-04-16 22:43

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=100)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_cast', models.DateField(default=django.utils.timezone.now)),
                ('num_samples', models.SmallIntegerField()),
                ('break_days', models.CharField(max_length=30)),
                ('strength', models.IntegerField()),
                ('status', models.SmallIntegerField(default=0)),
                ('technician', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
