# Generated by Django 3.0.5 on 2020-06-05 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sievesample',
            name='sample_day',
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='process_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
