# Generated by Django 3.0.5 on 2020-06-06 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20200605_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='technician',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('groups__name', 'Manager'), ('groups__name', 'Technician'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
