# Generated by Django 3.0.5 on 2020-04-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20200417_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concretereport',
            name='strength',
        ),
        migrations.AlterField(
            model_name='concretereport',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Technician'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConcreteSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_day', models.DateField()),
                ('break_day', models.DateField()),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ConcreteReport')),
            ],
        ),
    ]
