# Generated by Django 3.0.5 on 2020-06-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200605_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstandard',
            name='standard_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'compression'), (1, 'sieve')], default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReportStandardParametersSieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_120', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 120 mm')),
                ('min_80', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 80 mm')),
                ('min_40', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 40 mm')),
                ('min_20', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 20 mm')),
                ('min_10', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 10 mm')),
                ('min_5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 5 mm')),
                ('min_1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 1 mm')),
                ('min_05', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 0.5 mm')),
                ('min_025', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Passing 0.25 mm')),
                ('max_120', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 120 mm')),
                ('max_80', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 80 mm')),
                ('max_40', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 40 mm')),
                ('max_20', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 20 mm')),
                ('max_10', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 10 mm')),
                ('max_5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 5 mm')),
                ('max_1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 1 mm')),
                ('max_05', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 0.5 mm')),
                ('max_025', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Passing 0.25 mm')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ReportStandard')),
            ],
        ),
        migrations.CreateModel(
            name='ReportStandardParametersCompression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.DecimalField(decimal_places=2, max_digits=6)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ReportStandard')),
            ],
        ),
    ]
