# Generated by Django 3.0.5 on 2020-06-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200609_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstandard',
            name='standard_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Compression'), (1, 'Sieve')]),
        ),
        migrations.AlterField(
            model_name='reportstandardparameterscompression',
            name='standard',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ReportStandard'),
        ),
    ]
