# Generated by Django 3.0.5 on 2020-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200420_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretereport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concretesample',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
