# Generated by Django 3.0.5 on 2020-06-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200609_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstandardparameterscompression',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compression', to='dashboard.ReportStandard'),
        ),
        migrations.AlterField(
            model_name='reportstandardparameterssieve',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sieve', to='dashboard.ReportStandard'),
        ),
    ]
