# Generated by Django 3.0.5 on 2020-06-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200612_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sievesample',
            name='dry_weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_025',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='0.25 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_05',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='0.5 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='1 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='10 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_120',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='120 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_20',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='20 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_40',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='40 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='5 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='mm_80',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='80 mm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='moisture_content',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='result',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pass'), (1, 'Warning'), (2, 'Fail')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='wet_weight',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
    ]
