# Generated by Django 3.0.5 on 2020-06-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200617_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretesample',
            name='result',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Fail'), (1, 'Pass')], null=True),
        ),
        migrations.AlterField(
            model_name='sievesample',
            name='result',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Fail'), (1, 'Pass')]),
        ),
    ]
