# Generated by Django 3.0.5 on 2020-04-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_concretesample_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretesample',
            name='break_day_num',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
