# Generated by Django 3.0.5 on 2020-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_concretesample_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretereport',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
