# Generated by Django 3.0.5 on 2020-05-20 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20200519_1701'),
        ('dashboard', '0012_auto_20200514_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='SieveReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_sampled', models.DateField(default=django.utils.timezone.now)),
                ('num_samples', models.SmallIntegerField()),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Project')),
                ('technician', models.ForeignKey(limit_choices_to={'groups__name': 'Technician'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
