# Generated by Django 3.0.5 on 2020-05-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200529_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concretereport',
            name='break_days',
        ),
        migrations.RemoveField(
            model_name='concretereport',
            name='num_samples',
        ),
        migrations.AlterField(
            model_name='concretesample',
            name='break_day_num',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
