# Generated by Django 3.0.5 on 2020-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200529_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concretesample',
            old_name='break_day',
            new_name='break_date',
        ),
        migrations.RenameField(
            model_name='concretesample',
            old_name='cast_day',
            new_name='cast_date',
        ),
        migrations.RemoveField(
            model_name='concretesample',
            name='break_day_num',
        ),
        migrations.AddField(
            model_name='concretesample',
            name='days_break',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
