# Generated by Django 3.0.5 on 2020-05-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200529_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretesample',
            name='break_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concretesample',
            name='cast_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
